### ISSUE TITLE
Documentation for the various API calls

### ISSUE THREAD

**Issue by dhowe** [Madek/madek-api#4]
Where can I find this? I'm specifically interested in functions that write rather than read
thanks

**Comment by DrTom** [comment]
You will find some documentation under `/api/docs/` on your instance. 

The current API is very limited with respect to writing (users, people, groups, ...). No resources concerning MediaEntries, Vocabularies, MetaData, .... are available for writing. 

There is a new API in development which features writeable resources across.

**Comment by dhowe** [comment]
thanks @DrTom is there somewhere I can follow progress on the new API ( a branch or roadmap doc ) ?

**Comment by DrTom** [comment]
There is a Project on GH https://github.com/Madek/madek-api-v2
